### ISSUE TITLE
xcode 7 compile problems. 

### ISSUE THREAD

**Issue by johndpope** [vandadnp/iOS-8-Swift-Programming-Cookbook#15]
![screen shot 2015-06-29 at 1 37 23 pm](https://cloud.githubusercontent.com/assets/289994/8400169/6509b9ac-1e5d-11e5-97b7-88d69bf270d1.png)

**Comment by vandadschibsted** [comment]
Thanks for this. I fixed it here https://github.com/vandadnp/iOS-8-Swift-Programming-Cookbook/commit/448a560aa73b5afffee1ac4e41c4db5d8ea79fe7
