### ISSUE TITLE
Extra argument 'type' in call

### ISSUE THREAD

**Issue by datomnurdin** [vandadnp/iOS-8-Swift-Programming-Cookbook#16]
I got this error message

```
/Users/MNurdin/Documents/Github/iOS-8-Swift-Programming-Cookbook/chapter-multimedia/Playing Video Files/Playing Video Files/ViewController.swift:120:26: Extra argument 'type' in call
```

In this ViewController file

```
override func viewDidLoad() {
    super.viewDidLoad()

    playButton = UIButton(type: .System) //error message here
```

Please advice. Thank you.

**Comment by vandadnp** [comment]
Hi,

The HEAD of the master branch, where you are at, at the moment, is compatible with Swift 2.0 and Xcode 7 Beta 1. If you are on Xcode 6 and iOS 8 SDK, check this release out

https://github.com/vandadnp/iOS-8-Swift-Programming-Cookbook/releases/tag/xcode-6.3-beta-2-6D532l

**Comment by datomnurdin** [comment]
Thanks!!
