### ISSUE TITLE
Accepting User Text Input with UITextField project 

### ISSUE THREAD

**Issue by yarshure** [vandadnp/iOS-8-Swift-Programming-Cookbook#7]
Unknown class _TtC42Accepting_User_Text_Input_with_UITextField14ViewController in Interface Builder file.

iOS Simulator

**Comment by vandadnp** [comment]
Thanks for raising this. I fixed it here:

https://github.com/vandadnp/iOS-8-Swift-Programming-Cookbook/commit/90caf539fc102d60799b2f6c152c6a2c4d0604b9
